export const MIDDLEWARE_PRODUCTS_LIST_LOAD = 'MIDDLEWARE_PRODUCTS_LIST_LOAD';

export const SAVE_PRODUCTS_LIST = 'SAVE_PRODUCTS_LIST';

export const MIDDLEWARE_REMOVE_PRODUCT = 'MIDDLEWARE_REMOVE_PRODUCT';

export const MIDDLEWARE_ADD_PRODUCT = 'MIDDLEWARE_ADD_PRODUCT';

export const MIDDLEWARE_UPDATE_PRODUCT = 'MIDDLEWARE_UPDATE_PRODUCT';

export const LOADING = 'LOADING';
